[fonts]
size = 20

[bindings]
keys = [
  { key = "1", with = "alt", action = "SelectTab(0)" },
  { key = "2", with = "alt", action = "SelectTab(1)" },
  { key = "3", with = "alt", action = "SelectTab(2)" },
  { key = "4", with = "alt", action = "SelectTab(3)" },
  { key = "5", with = "alt", action = "SelectTab(4)" },
  { key = "6", with = "alt", action = "SelectTab(5)" },
  { key = "7", with = "alt", action = "SelectTab(6)" },
  { key = "8", with = "alt", action = "SelectTab(7)" },
  { key = "9", with = "alt", action = "SelectTab(8)" },
]
