repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-json
    - id: check-yaml
    - id: requirements-txt-fixer
    - id: pretty-format-json
      args: [--autofix, --indent=4, --no-ensure-ascii]
